const dailyMoods = [
  {
    name: '- Happy',
    population: 0,
    color: 'rgba(131, 167, 234, 1)',
    legendFontColor: '#a178b1',
    legendFontSize: 12,
  },
  {
    name: '- Sad',
    population: 150,
    color: '#F00',
    legendFontColor: '#a178b1',
    legendFontSize: 12,
  },
  {
    name: '- Meh',
    population: 400,
    color: '#4da550',
    legendFontColor: '#a178b1',
    legendFontSize: 12,
  },
  {
    name: '- Cheese',
    population: 250,
    color: '#ffffff',
    legendFontColor: '#a178b1',
    legendFontSize: 12,
  },
  {
    name: '- Excited',
    population: 500,
    color: 'rgb(0, 0, 255)',
    legendFontColor: '#a178b1',
    legendFontSize: 12,
  },
];

const weeklyMoods = [
  {
    name: '- Happy',
    population: 25,
    color: 'rgba(131, 167, 234, 1)',
    legendFontColor: '#a178b1',
    legendFontSize: 12,
  },
  {
    name: '- Sad',
    population: 35,
    color: '#F00',
    legendFontColor: '#a178b1',
    legendFontSize: 12,
  },
  {
    name: '- Meh',
    population: 17,
    color: '#a54d8f',
    legendFontColor: '#a178b1',
    legendFontSize: 12,
  },
  {
    name: '- Angry',
    population: 9,
    color: '#4da550',
    legendFontColor: '#a178b1',
    legendFontSize: 12,
  },
  {
    name: '- Hopeful',
    population: 33,
    color: '#d0ff00',
    legendFontColor: '#a178b1',
    legendFontSize: 12,
  },
  {
    name: '- Doubtful',
    population: 12,
    color: '#ffa600',
    legendFontColor: '#a178b1',
    legendFontSize: 12,
  },
  {
    name: '- Cheese',
    population: 43,
    color: '#e2e05f',
    legendFontColor: '#a178b1',
    legendFontSize: 12,
  },
  {
    name: '- Neutral',
    population: 40,
    color: 'rgb(38, 202, 207)',
    legendFontColor: '#a178b1',
    legendFontSize: 12,
  },
  {
    name: '- Excited',
    population: 7,
    color: 'rgb(38, 207, 156)',
    legendFontColor: '#a178b1',
    legendFontSize: 12,
  },
];

const monthlyMoods = [
  {
    name: '- Happy',
    population: 55,
    color: 'rgba(131, 167, 234, 1)',
    legendFontColor: '#a178b1',
    legendFontSize: 12,
  },
  {
    name: '- Sad',
    population: 75,
    color: '#F00',
    legendFontColor: '#a178b1',
    legendFontSize: 12,
  },
  {
    name: '- Meh',
    population: 100,
    color: '#a54d8f',
    legendFontColor: '#a178b1',
    legendFontSize: 12,
  },
  {
    name: '- Angry',
    population: 25,
    color: '#4da550',
    legendFontColor: '#a178b1',
    legendFontSize: 12,
  },
  {
    name: '- Hopeful',
    population: 45,
    color: '#d0ff00',
    legendFontColor: '#a178b1',
    legendFontSize: 12,
  },
  {
    name: '- Doubtful',
    population: 60,
    color: '#ffa600',
    legendFontColor: '#a178b1',
    legendFontSize: 12,
  },
  {
    name: '- Cheese',
    population: 80,
    color: '#e2e05f',
    legendFontColor: '#a178b1',
    legendFontSize: 12,
  },
  {
    name: '- Neutral',
    population: 50,
    color: 'rgb(38, 202, 207)',
    legendFontColor: '#a178b1',
    legendFontSize: 12,
  },
  {
    name: '- Excited',
    population: 69,
    color: 'rgb(38, 207, 156)',
    legendFontColor: '#a178b1',
    legendFontSize: 12,
  },
];

export { dailyMoods, weeklyMoods, monthlyMoods };
